---
stages: [check-pr, build]

# check-pr:
#   # Check the current commit message for compliance with commitizen
#   stage: check-pr
#   image: alpine:latest
#   inherit:
#     variables: false
#   script:
#     - apk add --no-cache --upgrade py3-pip
#     - pip install -U commitizen
#     - cz check --message "$CI_COMMIT_MESSAGE" >/tmp/cz_check || true # why does it return 1 if its actually 0?
#     - grep "successful" /tmp/cz_check # ugly hack to workaround the above issue
#   rules:
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#     - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

build-builder:
  # Used to deploy a new base Docker image for building purposes
  # this one runs once per day via pipeline schedules
  stage: build
  image: docker:24-cli
  services:
    - name: docker:24-dind
      alias: docker-daemon
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$CI_REGISTRY_IMAGE/builder:latest" ./builder-container
    - docker push "$CI_REGISTRY_IMAGE/builder:latest"
  tags: ["dind"]
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker-daemon:2375/
    DOCKER_TLS_CERTDIR: ""

build-manager:
  stage: build
  image: docker:24-cli
  services:
    - name: docker:24-dind
      alias: docker-daemon
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$CI_REGISTRY_IMAGE/manager:latest" .
    - docker push "$CI_REGISTRY_IMAGE/manager:latest"
  tags: ["dind"]
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker-daemon:2375/
    DOCKER_TLS_CERTDIR: ""
  rules:
  - if: $UPDATE_BUILDER != "1"