FROM node:22.4-alpine AS builder

WORKDIR /build
COPY . /build

RUN yarn install
RUN yarn build

FROM quay.io/podman/stable:latest

RUN yum install -y nodejs autossh netcat sudo
WORKDIR /app
COPY --from=builder /build/config /app/config
COPY ./manager-container/entry_point-podman.sh /entry_point.sh
RUN chmod +x /entry_point.sh
COPY --from=builder /build/dist /app
COPY --from=builder /build/node_modules /app/node_modules

ENTRYPOINT ["/entry_point.sh"]
